### ISSUE TITLE
Default biome setting for island based Nether

### ISSUE THREAD

**Issue by Vimppura69** [BentoBoxWorld/AcidIsland#101]
**Feature request related to a problem**
After 1.16 Minecraft there is a new Nether. New Nether contains multiple biomes, that also appear naturally into island-based Nether. That means that different people have different biomes at their Nether Islands. And because they all doesn't have the same biome, only some players have access to ex. Piglins to trade valuable materials with and that makes different players' islands unequal.

**The solution I'd like**
Just like the Overworld, I suggest there should be ''default-biome" -setting at the config for also for the Nether that allows to decide the default biome for the whole world. I believe it also needs a separate setting that allows to enable/disable the default-biome setting depending on whether you use island based Nether or the vanilla Nether. (or then you just make sure that default-biome settings affect the world only if it is island based)

**Alternatives I've considered**
I've also considered to use the biome-addon so players could switch their island's biome by themselves. There is just some problems like
- I'm not sure if it even supports 1.16 biomes yet
- We only want one biome for players to use and only in the Nether because we have built our challenges for specific biome settings only.

**Comment by tastybento** [comment]
This already exists. Check your config.yml for AcidIsland (If you cannot see this, then make sure you're on the latest version):

Around line 142:
```
  # The default biome for the overworld
  default-biome: WARM_OCEAN
  # The default biome for the nether world (this may affect what mobs can spawn)
  default-nether-biome: NETHER_WASTES
  # The default biome for the end world (this may affect what mobs can spawn)
  default-end-biome: THE_END
```
