### ISSUE TITLE
If you add rain and seawater will make the equipment lose durability, it will be more fun

### ISSUE THREAD

**Issue by xiaoyilk** [BentoBoxWorld/AcidIsland#114]
### Is your feature request related to a problem?

If you add rain and seawater will make the equipment lose durability, it will be more fun

### Describe the solution you'd like.

If you add rain and seawater will make the equipment lose durability, it will be more fun

### Describe alternatives you've considered.

If you add rain and seawater will make the equipment lose durability, it will be more fun

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

I don't speak English well, so I don't know what these checkboxes do

**Comment by tastybento** [comment]
You can have items dissolve in acid by this setting:

https://github.com/BentoBoxWorld/AcidIsland/blob/86783b5516b3a0059d7cff6709d2b8f0499fcb69/src/main/resources/config.yml#L30

It only is for acid, not rain.

Armor also loses durability in the sea.
