### ISSUE TITLE
Create Biome Floor

### ISSUE THREAD

**Issue by QueenFoxo** [BentoBoxWorld/AcidIsland#125]
### Is your feature request related to a problem?

Creating a custom island/skyblock it limited when the player can only go as far as the custom 'creation' is made, past this the biome/water drops to the void.

### Describe the solution you'd like.

Create a biome/ocean floor sand/gravel blocks in acid island so that it has more attention to detail and easier for custom islands to be unlimitedly created.

### Describe alternatives you've considered.

Finding plugins that create a biome floor, but they do not Collab with Bskyblock/Acidisland

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tirangaming** [comment]
It would be a pretty neat feature. I also thought of this idea, It would be cool to have for example sand and then one block height of water and then the island. 👍

**Comment by tastybento** [comment]
This is in progress. One element that will be needed is the new island deletion system that is being developed that will recreate the chunks after they are deleted. However, it is in development.

**Comment by tastybento** [comment]
Latest version has an option in config.yml to have this.
