### ISSUE TITLE
Option to turn off ocean in nether/end

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#13]
**Is your feature request related to a problem? Please describe.**
In the original AcidIsland; the Nether was unique to the overworld in that there was no way to use water there except through the use of glitches. Bentobox partially takes this unique feeling away by adding an ocean to the nether (and now, the end).

**Describe the solution you'd like**
An option in the configuration to disable ocean generation in the nether and the end.

**Describe alternatives you've considered**
No alternatives.

**Comment by tastybento** [comment]
Yes, this was a conscious decision to make the AcidIsland nether and end different from the BSkyBlock nether and end. It could be set up to be config option though.
For lava, that could be an option, but it will give players unlimited lava as a result which they can transport back to the overworld to make obsidian.

**Comment by TheWranger** [comment]
On my server, the Nether was always sorta treated as the world where you couldn't have water, meaning you had to be more creative with their grinders in there. Adding an ocean sorta destroys that feeling as while people still can't place their own water in there, they have an unlimited source of it for grinders and whatnot.
I guess The End comes more down to personal preference though.

**Comment by Manu5656** [comment]
Yes, please immediately add an option to turn off the water in the nether and in the end otherwise I can not open my server!

**Comment by tastybento** [comment]
I’ll add a sea height setting for each world so it can be set to 0 or any other value.

**Comment by Manu5656** [comment]
Perfect, I thank you. You are my savior 🤣

**Comment by Poslovitch** [comment]
@tastybento Maybe it should be done in BentoBox? I don't remember if sea-height is part of WorldSettings or not.

**Comment by tastybento** [comment]
@Poslovitch sea height is a world setting. It's there so that other add ons can check what the height is if required, e.g., Level add-on gives more points if your blocks are below sea level. For nether and end sea levels I just kept them in AcidIsland for now. I'm not sure if these items should go in WorldSettings or not.
