### ISSUE TITLE
acid island generate below y=0 but cant go below it

### ISSUE THREAD

**Issue by doragoncraft** [BentoBoxWorld/AcidIsland#131]
### Expected behavior

to be able to go to y=-63 

### Observed/Actual behavior

bounces player up when the hit y=0

### Steps/models to reproduce

swim down

### BentoBox version

mail.com ran command: bbox version
05.01 22:36:12 [Server] [INFO] Running PAPER Invalid.
05.01 22:36:12 [Server] [INFO] BentoBox version: 1.21.1
05.01 22:36:12 [Server] [INFO] Database: JSON
05.01 22:36:12 [Server] [INFO] Loaded Game Worlds:
05.01 22:36:12 [Server] [INFO] acidisland_world (AcidIsland): Overworld, Nether, The End
05.01 22:36:12 [Server] [INFO] bskyblock_world (BSkyBlock): Overworld, Nether, The End
05.01 22:36:12 [Server] [INFO] oneblock_world (OneBlock): Overworld, Nether, The End
05.01 22:36:12 [Server] [INFO] skygrid-world (SkyGrid): Overworld, Nether, The End
05.01 22:36:12 [Server] [INFO] Loaded Addons:
05.01 22:36:12 [Server] [INFO] AcidIsland 1.16.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] AOneBlock 1.11.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Bank 1.4.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Biomes 2.0.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] BSkyBlock 1.16.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Challenges 1.0.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] ControlPanel 1.13.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] DimensionalTrees 1.6.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] InvSwitcher 1.11.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] IslandFly 1.9.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Level 2.9.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Likes 2.3.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] SkyGrid 1.18.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Visit 1.4.0 (ENABLED)
05.01 22:36:12 [Server] [INFO] Warps 1.12.0 (ENABLED)

### Plugin list

Plugins (55): AdvancedOreGen, AncientGates, AutoCraft, BentoBox, Bookshelf, BuycraftX, CoreProtect, CrateReloaded, DCAntiop, DCSleep, DCVouchers, DeluxeHub, DeluxeTags, Denizen, DoragonHub, Doragonspy, dynmap, Economobs, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, F3NPerm, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, HolographicDisplays, JellyLegs, LuckPerms, MoneyHunters, Multiverse-Core, Multiverse-NetherPortals, NexEngine, PlaceholderAPI, PlayerVaults, PlotSquared, PluginManager, ServerSelectorX, ShopGUIPlus, SilkSpawners_v2, Skript, SmoothTimber, spark, StackMob, TextFormatting, TopBalance, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Wild, WorldBorder, WorldEditSelectionVisualizer, WorldGuard

**Comment by tastybento** [comment]
Yes, I have fixed this in a branch but is not released yet.

**Comment by tastybento** [comment]
Fixed in the latest release.
