### ISSUE TITLE
Add a option to change stone generator affect by acid water

### ISSUE THREAD

**Issue by LittleHed** [BentoBoxWorld/AcidIsland#137]
### Is your feature request related to a problem?

I don't want the acid to break my stone generator, can there be a option in config that toggle it?My players need it to make the redstone machine

### Describe the solution you'd like.

 Add a option to change stone generator affect by acid water

### Describe alternatives you've considered.

I have not see any options in config that can change it 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

![image](https://user-images.githubusercontent.com/58099834/233834835-0a2b2945-629a-453a-b7b3-b39825cc375c.png)

**Comment by tastybento** [comment]
The challenge here is that if that’s turned off, then the acid ocean/sea can easily be paved by just pouring lava on in and the game becomes too easy. 

Is the issue that players need clean stone? Maybe you can give it as a challenge reward or sell it in a store?

**Comment by LittleHed** [comment]
the solution of acid ocean also affect the clean stone generator(which is similar to the cobblestone generator)

**Comment by LittleHed** [comment]
I have disabled the acid damage because I want the game be much easier.  Since my server is on vanilla style, I do not want to disable such that generator

**Comment by BONNe** [comment]
I think a world flag or setting in config would be acceptable as some servers may want only world generator without any.acid part

**Comment by tastybento** [comment]
> I think a world flag or setting in config would be acceptable as some servers may want only world generator without any.acid part

There already is a setting to turn off acid damage. And if it is set to zero then nothing happens to the generation of stone via the ocean.

> I have disabled the acid damage because I want the game be much easier. Since my server is on vanilla style, I do not want to disable such that generator

I don't quite understand the English, but it sounds like you've disabled acid damage, so there should be no issue. Is there anything to do here?

**Comment by LittleHed** [comment]
hmm my problem. I try to disable both acid damage and potioneffect, then after restarting the server, it is fixed.
