### ISSUE TITLE
World Generation shouldn't happen in Nether (and probably End)

### ISSUE THREAD

**Issue by MeFisto94** [BentoBoxWorld/AcidIsland#149]
### Expected behavior

When in the nether, there shouldn't be sand banks generating.
There shouldn't be Nether Fortresses generating and clipping into the islands either, or even less so.

### Observed/Actual behavior

Structures generate and the floor is sand (below the lava/water level)

### Steps/models to reproduce

Toggle the setting to allow for BentoBox/AI to use the regular terrain generation instead of a void world.
This works as expected in the overworld, but it's application in the nether feels weird.

### BentoBox version

[00:50:43 INFO]: Running PAPER 1.20.4.
[00:50:43 INFO]: BentoBox version: 2.0.0-SNAPSHOT-b2540
[00:50:43 INFO]: Database: JSON
[00:50:43 INFO]: Loaded Game Worlds:
[00:50:43 INFO]: islands (AcidIsland): Overworld, Nether, The End
[00:50:43 INFO]: Loaded Addons:
[00:50:43 INFO]: AcidIsland 1.18.2 (ENABLED)
[00:50:43 INFO]: Challenges 1.3.0-SNAPSHOT-b539 (ENABLED)
[00:50:43 INFO]: ControlPanel 1.13.1-SNAPSHOT-b61 (ENABLED)
[00:50:43 INFO]: Level 2.12.0 (ENABLED)

**Comment by tastybento** [comment]
So... it's not really a bug in that the sea bottom is supposed to be there, although I suppose the blocks could be nether rack for the Nether and End stone for the End. 
In regards to structures, those are turned on, but I could provide a config to turn them off. I'll investigate some more.

**Comment by tastybento** [comment]
Okay, I've made some changes. Feedback welcome. You can try the AcidIsland snapshot at ci.bentobox.world

**Comment by MeFisto94** [comment]
Hey, sorry for the late feedback. Indeed the changes work for me!
Also, reflecting again, I realized it is indeed much more about a feature request than an actual bug.
Maybe to elaborate a bit (as _maybe_ those options are interesting per-world):
For the overworld, I really like the generation of the amethyst caves. There are no structures that are otherwise generated.
I guess this may be a coincidence of biome and what structures are generated? i.e. no villages?

For the nether, though, islands generated in the midst of nether bastions/fortresses, essentially making this setting useless for me.

So, indeed, this is fixed, but potentially one may want to differ on a per world basis, but I guess for me caves: yes and structures: no, should work.

Thanks for the fast fix!
