### ISSUE TITLE
Rain broken on Restart

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#15]
**Description**
When the server starts up and there is already rain present in the AcidIsland world, there is no damage given from it and it doesn't function like normal acid rain.

**Steps to reproduce the behavior:**
1. Set acidisland world to raining
2. Restart server
3. The rain will no longer deal damage
4. Get ready for players messaging you asking you why the rain isn't dealing damage

**Expected behavior**
The rain should deal damage

**Server Information:**
Paper Build 488

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Flat file
 - OS: Linux
 - Java Version: Java 8
 - BentoBox version: 0.18.0
 - Addons installed?
```
23.12 19:35:59 [Server] INFO Bentobox version: 0.18.0
23.12 19:35:59 [Server] INFO Loaded Game Worlds:
23.12 19:35:59 [Server] INFO islands2 (AcidIsland)
23.12 19:35:59 [Server] INFO Loaded Add-Ons
23.12 19:35:59 [Server] INFO AcidIsland 0.5.0
```
 - Other plugins? Happens without anything else installed.

**Additional context**
This was also an issue in 1.12 AcidIsland but I didn't worry about it too much then. But, I have several players message me whenever the server restarts and this happens and it would be nice if this could be fixed to solve the confusion instead of players constantly having to tell each other that this happens.

**Comment by tastybento** [comment]
Okay, good point. I'll look into this. I think there's a way to check the weather of a world.
