### ISSUE TITLE
EntityDamageByAcidEvent should be cancellable

### ISSUE THREAD

**Issue by Clexus** [BentoBoxWorld/AcidIsland#150]
### Is your feature request related to a problem?

no

### Describe the solution you'd like.

title

### Describe alternatives you've considered.

no

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
@Clexus Please check the SNAPSHOT build of 1.19.0 with changes in to allow canceling (see the PR).

**Comment by Clexus** [comment]
works
