### ISSUE TITLE
ItemDestroyByAcidEvent, ItemFillWithAcidEvent and PlayerDrinkAcidEvent don't work

### ISSUE THREAD

**Issue by Clexus** [BentoBoxWorld/AcidIsland#152]
### Expected behavior

work

### Observed/Actual behavior

At least I didn't see items destroyed by acid, and players drink bottle of acid water still alive
Also there's no options in config.yml

### Steps/models to reproduce

Try it

### BentoBox version

![image](https://github.com/BentoBoxWorld/AcidIsland/assets/62130504/8b1f2c91-ab09-431f-82f2-97f4e99675b1)
Sorry but I can't access console

**Comment by tastybento** [comment]
ItemDestroyByAcidEvent is called if an item is destroyed by acid. To turn that feature on, set this to more than 0:

https://github.com/BentoBoxWorld/AcidIsland/blob/7b232294ed290aa0300e8a1e37d049a155caca47/src/main/resources/config.yml#L31

ItemFillWithAcidEvent and PlayerDrinkAcidEvent were deprecated a long time ago and are never fired. They were left in just to help with backwards compatibility.
