### ISSUE TITLE
Armor Durability

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#17]
**Is your feature request related to a problem? Please describe.**
Armor helps protect against acid but takes no damage like it does for other things such as lava or mob attacks.

**Describe the solution you'd like**
An option in the configuration to make armor take durability damage every second the user is in acid. Maybe there could also be an option for acid rain?

**Comment by tastybento** [comment]
This could be done and ties in with the idea of the game.
