### ISSUE TITLE
Armor Protection

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#18]
**Is your feature request related to a problem? Please describe.**
I only just found out recently that armor naturally lowers the amount of damage that acid does (as there is no mention of this in the configuration). The problem with granting armor natural protection against acid is that it automatically grants people the perk of greatly reduced acid damage as they develop more.

**Describe the solution you'd like**
A much better system would be to make people have to develop specifically against acid by requiring things such as turtle hats, water breathing potions, conduits, and respiration helmets (https://github.com/BentoBoxWorld/AcidIsland/issues/8). There needs to be a config option to disable natural protection to acid.

**Alternatives you've considered**
At least mention somewhere in the configuration that armor naturally blocks damage from acid and acid rain.

**Comment by tastybento** [comment]
Armor protecting you from acid has been a part of AcidIsland since it was created and it is usually mentioned in the description of the game. Wearing more and better armor gives you better protection.

A understand how you'd like to change this, but as it's a part of this game, it's not something I'm going to change. Sorry.

**Comment by TheWranger** [comment]
@tastybento we have the ability to change damage from acid and control how much it hurts mobs, along with whether it will hurt chickens or not, but no way to choose whether armor provides protection against acid or not.

The problem I have is that once players acquire a decent set of armor; they stop caring about things like building shelter over areas to protect them from rain, especially if visitors are invincible. I wouldn't see this as an issue if a player specifically sought after a turtle hat to block acid damage but the way things currently are, everybody automatically gets better acid protection without trying, as they develop their islands more.

This is a bigger problem for servers that set their acid damage lower because new players die too often because of it and then ragequit the server, I even set it as low as 4.
