### ISSUE TITLE
Problem with nether island

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#20]
Hi, I have this problem with the nether island. It is not loaded. The file format is correct (it has been saved with .schem, like the other schematics). What could be the problem? What should I check? I've tried everything so far 😓

`[18:20:42 ERROR]: [BentoBox] Tried to paste schem for AcidIsland_world_nether but the schem is not loaded!
[18:20:42 INFO]: [BentoBox] This might be due to an invalid schem format. Keep in mind that schems are not schematics.`

**Comment by Manu5656** [comment]
Help?

**Comment by tastybento** [comment]
How are you making the schem? It has to be made in-game using the admin schem command.

**Comment by Manu5656** [comment]
I used those commands. I did / acid schem pos1 / acid schem pos2 / acid schem copy / acid schem save nether-island

**Comment by tastybento** [comment]
When you reload (or start), what errors do you see in the console. Clearly the schem is not loading, so there is probably an error that says why.

Also, I've no idea what version of the game you are using so if you are not on the latest, then that may be the issue.

Finally, drag and drop the schem file (zip it) here and I'll see if I can see the problem.

**Comment by Manu5656** [comment]
I managed to solve. Before doing / acid schem copy was also done / acid schem origin. Thanks for the support! :)
