### ISSUE TITLE
/is command

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#26]
If I change the value "ai" with "is" all the commands do not work, as for example that of the challenges that can not be seen with / is challenges and with / to the challenges (It was better as before, directly with the command / co / challenges, I think it would be to reintrude, it is much more comfortable)

`  command:
    # Island Command. What command users will run to access their island
    island: ai`

**Comment by BONNe** [comment]
So, you should wait till BentoBox 1.1. It will be fixed there.
