### ISSUE TITLE
Turtle Acid Damage

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#29]
**Description**
Turtle take damage from acid

**Steps to reproduce the behavior:**
1. Spawn a turtle in acid

**Expected behavior**
Turtles shouldn't take damage in acid

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Flat file
 - OS: Linux
 - Java Version: Java 8
 - BentoBox version: 1.0
 - Addons installed? 
```
24.01 23:12:11 [Server] INFO Bentobox version: 1.0
24.01 23:12:11 [Server] INFO Loaded Game Worlds:
24.01 23:12:11 [Server] INFO islands3 (Islands)
24.01 23:12:11 [Server] INFO Loaded Add-Ons
24.01 23:12:11 [Server] INFO AcidIsland 1.0
24.01 23:12:11 [Server] INFO Biomes 0.4.0
24.01 23:12:11 [Server] INFO Level 0.2.0
24.01 23:12:11 [Server] INFO Challenges 0.3.0
```

**Additional context**
Turtles will swim around in water so if this is intentional then I think it should be changed.

**Comment by tastybento** [comment]
Oops
