### ISSUE TITLE
Rain damage in The End

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#32]
**Description**
For some reason there is constant rain damage in The End.

**Steps to reproduce the behavior:**
1. Go to The End

**Expected behavior**
Players will not take rain damage in the end

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Flat File
 - Linux
 - Java 8
 - BentoBox version 1.2.1
 -
```
03.02 07:18:58 [Server] INFO AcidIsland 1.2.1-SNAPSHOT
03.02 07:18:58 [Server] INFO Biomes 0.4.0
03.02 07:18:58 [Server] INFO Level 1.1-SNAPSHOT
03.02 07:18:58 [Server] INFO Challenges 0.5.0-SNAPSHOT
```

**Additional context**
Issue also occurred on AcidIsland 1.0 with bentobox 1.0 and bentobox 1.1, not a new bug.

**Comment by TheWranger** [comment]
Nevermind, the player doesn't always take damage but it seems to be occasional - as if the plugin thinks it's supposed to be raining in the end at times.

**Comment by BONNe** [comment]
Im not sure, but in the end it should not rain, as in the nether....

**Comment by TheWranger** [comment]
> Im not sure, but in the end it should not rain, as in the nether....

Ye that's the point, but AcidIsland seems to think it's raining.

**Comment by tastybento** [comment]
Thanks for the report.
