### ISSUE TITLE
Acid rain damage doesn't go away on entering dry biome

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#35]
**Description**
If a player is in a non-dry biome and its raining, then goes inside a dry biome while it's still raining; they will still get hurt by acid rain. 

**Steps to reproduce the behavior:**
1. Stand in a non-dry biome (ocean?)
2. Turn on rain
3. Go into a dry biome (desert?)
4. Still get hurt by acid rain

**Expected behavior**
When the player enters the dry biome, the acid rain damage will go away.

**Server Information:**
Not relevant

**Additional context**
Issue was also present in the old AcidIsland (tested on 1.12.2).
This issue is more noticeably for servers that use the addon alongside the biomes addon.

**Comment by BONNe** [comment]
So, YOU SHOULD add BentoBox version output.
As I am sure, that @tastybento fixed it in one of snapshots!!!

**Comment by Poslovitch** [comment]
Yep, the fix's here: https://github.com/BentoBoxWorld/AcidIsland/commit/8ee81763d196c05abf4816268c92542915c263fc

**Comment by TheWranger** [comment]
I am already running that snapshot, that fix was regarding acid rain still doing damage in certain biomes, not regarding entering of dry biomes not stopping acid damage.

**Comment by TheWranger** [comment]
Tested and confirmed to still be a bug on the latest version of AcidIsland.
```
12.02 04:50:46 [Server] INFO Bentobox version: 1.2.1
12.02 04:50:46 [Server] INFO Loaded Game Worlds:
12.02 04:50:46 [Server] INFO islands2 (Islands)
12.02 04:50:46 [Server] INFO Loaded Add-Ons
12.02 04:50:46 [Server] INFO AcidIsland 1.3.0-SNAPSHOT
12.02 04:50:46 [Server] INFO Biomes 0.4.0
12.02 04:50:46 [Server] INFO Level 1.1-SNAPSHOT
12.02 04:50:46 [Server] INFO Challenges 0.5.0-SNAPSHOT
```

**Comment by tastybento** [comment]
thanks for the report @TheWranger.

**Comment by tastybento** [comment]
Should be fixed now. Please test.

**Comment by TheWranger** [comment]
Yea, it's working as it should be now, thanks.
