### ISSUE TITLE
Falling snow acid damage

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#38]
**Is your feature request related to a problem? Please describe.**
Falling snow already has its own effect on the environment and it can a bit annoying for players if it also causes acid rain damage to them.

**Describe the solution you'd like**
A configuration option to disable acid rain damage for falling snow. Or maybe just completely disable falling snow rain damage?
This will also make cold biomes more appealing to players as they will provide some protection against rain. 

**Additional context**
Some biomes like the frozen ocean will have random patches of rain and snow, though I'd imagine that the falling snow is separable from rain as only the falling snow will generate snow and ice beneath it.

**Comment by tastybento** [comment]
Isn't snow just frozen acid? ;-)

**Comment by TheWranger** [comment]
Ye but we don't know steves body heat so we can't tell if it'll melt when it lands on him or not

**Comment by tastybento** [comment]
I think there's an API... hmmm, getPlayer().getBodyTemperature()... ;-)

**Comment by TheWranger** [comment]
Yea but snow still falls much slower than rain does ;)

**Comment by tastybento** [comment]
Done.
