### ISSUE TITLE
Enable Conduit

### ISSUE THREAD

**Issue by jiumen** [BentoBoxWorld/AcidIsland#39]
You seem to have missed Conduit

**Comment by tastybento** [comment]
I have no idea what that means, sorry.

**Comment by jiumen** [comment]
Maybe you can look at this           https://minecraft.gamepedia.com/Conduit

**Comment by jiumen** [comment]
Conduit Power （its a new buff ）,If the player has this buff,I think player should be immune to waters  damage.Have you forgotten this buff in version 1.13?

**Comment by tastybento** [comment]
Ahhhh, that conduit. Sorry. Thanks for the pointer. Yes, I'll add this.

**Comment by jiumen** [comment]
Thanks you
