### ISSUE TITLE
Snow still doing damage

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/AcidIsland#41]
**Description**
Snow still does damage to players

**Steps to reproduce the behavior:**
1. Go into FROZEN_OCEAN biome
2. Turn on rain
3. Stand in one of the snow patches

**Expected behavior**
Players should not take damage from snow

**Server Information:**

[Please complete the following information:]
 - Flat File
 - Linux
 - Java 8
16.02 19:24:16 [Server] INFO Bentobox version: 1.3.0-SNAPSHOT
16.02 19:24:16 [Server] INFO Loaded Game Worlds:
16.02 19:24:16 [Server] INFO islands2 (Islands)
16.02 19:24:16 [Server] INFO Loaded Add-Ons
16.02 19:24:16 [Server] INFO AcidIsland 1.3.0-SNAPSHOT
16.02 19:24:16 [Server] INFO Challenges 0.5.0-SNAPSHOT
16.02 19:24:16 [Server] INFO Biomes 0.5.0-SNAPSHOT
16.02 19:24:16 [Server] INFO Level 1.2.1-SNAPSHOT
16.02 19:24:16 [Server] INFO Limits 0.1.0-SNAPSHOT

**Additional context**
Only tested in FROZEN_OCEAN biome. Tested with latest version of AcidIsland and Bentobox as of now.

**Comment by tastybento** [comment]
Okay, I completely missed a whole load of biomes. I'm going to see if there's a numerical way to do this rather than listing biomes.

**Comment by tastybento** [comment]
Okay, done. Acid rain will not affect biomes with a temperature of < 0.1 or a humidity of 0.

Biome | Temperature | Humidity
---: | :---: | :---:
SNOWY_TAIGA | -0.50 | 0.4
SNOWY_TAIGA_HILLS | -0.50 | 0.4
SNOWY_TAIGA_MOUNTAINS | -0.50 | 0.4
SNOWY_TAIGA | -0.50 | 0.4
SNOWY_TAIGA_HILLS | -0.50 | 0.4
SNOWY_TAIGA_MOUNTAINS | -0.50 | 0.4
SNOWY_TAIGA | -0.50 | 0.4
SNOWY_TAIGA_HILLS | -0.50 | 0.4
SNOWY_TAIGA_MOUNTAINS | -0.50 | 0.4
FROZEN_OCEAN | 0.00 | 0.5
FROZEN_RIVER | 0.00 | 0.5
SNOWY_TUNDRA | 0.00 | 0.5
SNOWY_MOUNTAINS | 0.00 | 0.5
ICE_SPIKES | 0.00 | 0.5
FROZEN_OCEAN | 0.00 | 0.5
FROZEN_RIVER | 0.00 | 0.5
SNOWY_TUNDRA | 0.00 | 0.5
SNOWY_MOUNTAINS | 0.00 | 0.5
ICE_SPIKES | 0.00 | 0.5
FROZEN_OCEAN | 0.00 | 0.5
FROZEN_RIVER | 0.00 | 0.5
SNOWY_TUNDRA | 0.00 | 0.5
SNOWY_MOUNTAINS | 0.00 | 0.5
ICE_SPIKES | 0.00 | 0.5
SNOWY_BEACH | 0.05 | 0.3
MOUNTAINS | 0.20 | 0.3
MOUNTAIN_EDGE | 0.20 | 0.3
STONE_SHORE | 0.20 | 0.3
WOODED_MOUNTAINS | 0.20 | 0.3
GRAVELLY_MOUNTAINS | 0.20 | 0.3
MODIFIED_GRAVELLY_MOUNTAINS | 0.20 | 0.3
MOUNTAINS | 0.20 | 0.3
MOUNTAIN_EDGE | 0.20 | 0.3
STONE_SHORE | 0.20 | 0.3
WOODED_MOUNTAINS | 0.20 | 0.3
GRAVELLY_MOUNTAINS | 0.20 | 0.3
MODIFIED_GRAVELLY_MOUNTAINS | 0.20 | 0.3
MOUNTAINS | 0.20 | 0.3
MOUNTAIN_EDGE | 0.20 | 0.3
STONE_SHORE | 0.20 | 0.3
WOODED_MOUNTAINS | 0.20 | 0.3
GRAVELLY_MOUNTAINS | 0.20 | 0.3
MODIFIED_GRAVELLY_MOUNTAINS | 0.20 | 0.3
TAIGA | 0.25 | 0.8
TAIGA_HILLS | 0.25 | 0.8
TAIGA_MOUNTAINS | 0.25 | 0.8
GIANT_SPRUCE_TAIGA | 0.25 | 0.8
GIANT_SPRUCE_TAIGA_HILLS | 0.25 | 0.8
TAIGA | 0.25 | 0.8
TAIGA_HILLS | 0.25 | 0.8
TAIGA_MOUNTAINS | 0.25 | 0.8
GIANT_SPRUCE_TAIGA | 0.25 | 0.8
GIANT_SPRUCE_TAIGA_HILLS | 0.25 | 0.8
TAIGA | 0.25 | 0.8
TAIGA_HILLS | 0.25 | 0.8
TAIGA_MOUNTAINS | 0.25 | 0.8
GIANT_SPRUCE_TAIGA | 0.25 | 0.8
GIANT_SPRUCE_TAIGA_HILLS | 0.25 | 0.8
GIANT_TREE_TAIGA | 0.30 | 0.8
GIANT_TREE_TAIGA_HILLS | 0.30 | 0.8
GIANT_TREE_TAIGA | 0.30 | 0.8
GIANT_TREE_TAIGA_HILLS | 0.30 | 0.8
GIANT_TREE_TAIGA | 0.30 | 0.8
GIANT_TREE_TAIGA_HILLS | 0.30 | 0.8
OCEAN | 0.50 | 0.5
RIVER | 0.50 | 0.5
THE_END | 0.50 | 0.5
DEEP_OCEAN | 0.50 | 0.5
SMALL_END_ISLANDS | 0.50 | 0.5
END_MIDLANDS | 0.50 | 0.5
END_HIGHLANDS | 0.50 | 0.5
END_BARRENS | 0.50 | 0.5
WARM_OCEAN | 0.50 | 0.5
LUKEWARM_OCEAN | 0.50 | 0.5
COLD_OCEAN | 0.50 | 0.5
DEEP_WARM_OCEAN | 0.50 | 0.5
DEEP_LUKEWARM_OCEAN | 0.50 | 0.5
DEEP_COLD_OCEAN | 0.50 | 0.5
DEEP_FROZEN_OCEAN | 0.50 | 0.5
THE_VOID | 0.50 | 0.5
OCEAN | 0.50 | 0.5
RIVER | 0.50 | 0.5
THE_END | 0.50 | 0.5
DEEP_OCEAN | 0.50 | 0.5
SMALL_END_ISLANDS | 0.50 | 0.5
END_MIDLANDS | 0.50 | 0.5
END_HIGHLANDS | 0.50 | 0.5
END_BARRENS | 0.50 | 0.5
WARM_OCEAN | 0.50 | 0.5
LUKEWARM_OCEAN | 0.50 | 0.5
COLD_OCEAN | 0.50 | 0.5
DEEP_WARM_OCEAN | 0.50 | 0.5
DEEP_LUKEWARM_OCEAN | 0.50 | 0.5
DEEP_COLD_OCEAN | 0.50 | 0.5
DEEP_FROZEN_OCEAN | 0.50 | 0.5
THE_VOID | 0.50 | 0.5
OCEAN | 0.50 | 0.5
RIVER | 0.50 | 0.5
THE_END | 0.50 | 0.5
DEEP_OCEAN | 0.50 | 0.5
SMALL_END_ISLANDS | 0.50 | 0.5
END_MIDLANDS | 0.50 | 0.5
END_HIGHLANDS | 0.50 | 0.5
END_BARRENS | 0.50 | 0.5
WARM_OCEAN | 0.50 | 0.5
LUKEWARM_OCEAN | 0.50 | 0.5
COLD_OCEAN | 0.50 | 0.5
DEEP_WARM_OCEAN | 0.50 | 0.5
DEEP_LUKEWARM_OCEAN | 0.50 | 0.5
DEEP_COLD_OCEAN | 0.50 | 0.5
DEEP_FROZEN_OCEAN | 0.50 | 0.5
THE_VOID | 0.50 | 0.5
BIRCH_FOREST | 0.60 | 0.6
BIRCH_FOREST_HILLS | 0.60 | 0.6
TALL_BIRCH_FOREST | 0.60 | 0.6
TALL_BIRCH_HILLS | 0.60 | 0.6
BIRCH_FOREST | 0.60 | 0.6
BIRCH_FOREST_HILLS | 0.60 | 0.6
TALL_BIRCH_FOREST | 0.60 | 0.6
TALL_BIRCH_HILLS | 0.60 | 0.6
BIRCH_FOREST | 0.60 | 0.6
BIRCH_FOREST_HILLS | 0.60 | 0.6
TALL_BIRCH_FOREST | 0.60 | 0.6
TALL_BIRCH_HILLS | 0.60 | 0.6
FOREST | 0.70 | 0.8
WOODED_HILLS | 0.70 | 0.8
DARK_FOREST | 0.70 | 0.8
FLOWER_FOREST | 0.70 | 0.8
DARK_FOREST_HILLS | 0.70 | 0.8
FOREST | 0.70 | 0.8
WOODED_HILLS | 0.70 | 0.8
DARK_FOREST | 0.70 | 0.8
FLOWER_FOREST | 0.70 | 0.8
DARK_FOREST_HILLS | 0.70 | 0.8
FOREST | 0.70 | 0.8
WOODED_HILLS | 0.70 | 0.8
DARK_FOREST | 0.70 | 0.8
FLOWER_FOREST | 0.70 | 0.8
DARK_FOREST_HILLS | 0.70 | 0.8
PLAINS | 0.80 | 0.4
BEACH | 0.80 | 0.4
SUNFLOWER_PLAINS | 0.80 | 0.4
PLAINS | 0.80 | 0.4
BEACH | 0.80 | 0.4
SUNFLOWER_PLAINS | 0.80 | 0.4
PLAINS | 0.80 | 0.4
BEACH | 0.80 | 0.4
SUNFLOWER_PLAINS | 0.80 | 0.4
SWAMP | 0.80 | 0.9
SWAMP_HILLS | 0.80 | 0.9
SWAMP | 0.80 | 0.9
SWAMP_HILLS | 0.80 | 0.9
SWAMP | 0.80 | 0.9
SWAMP_HILLS | 0.80 | 0.9
MUSHROOM_FIELDS | 0.90 | 1.0
MUSHROOM_FIELD_SHORE | 0.90 | 1.0
MUSHROOM_FIELDS | 0.90 | 1.0
MUSHROOM_FIELD_SHORE | 0.90 | 1.0
MUSHROOM_FIELDS | 0.90 | 1.0
MUSHROOM_FIELD_SHORE | 0.90 | 1.0
JUNGLE_EDGE | 0.95 | 0.8
MODIFIED_JUNGLE_EDGE | 0.95 | 0.8
JUNGLE_EDGE | 0.95 | 0.8
MODIFIED_JUNGLE_EDGE | 0.95 | 0.8
JUNGLE_EDGE | 0.95 | 0.8
MODIFIED_JUNGLE_EDGE | 0.95 | 0.8
JUNGLE | 0.95 | 0.9
JUNGLE_HILLS | 0.95 | 0.9
MODIFIED_JUNGLE | 0.95 | 0.9
JUNGLE | 0.95 | 0.9
JUNGLE_HILLS | 0.95 | 0.9
MODIFIED_JUNGLE | 0.95 | 0.9
JUNGLE | 0.95 | 0.9
JUNGLE_HILLS | 0.95 | 0.9
MODIFIED_JUNGLE | 0.95 | 0.9
SAVANNA_PLATEAU | 1.00 | 0.0
SHATTERED_SAVANNA_PLATEAU | 1.00 | 0.0
SAVANNA_PLATEAU | 1.00 | 0.0
SHATTERED_SAVANNA_PLATEAU | 1.00 | 0.0
SAVANNA_PLATEAU | 1.00 | 0.0
SHATTERED_SAVANNA_PLATEAU | 1.00 | 0.0
SHATTERED_SAVANNA | 1.10 | 0.0
SHATTERED_SAVANNA | 1.10 | 0.0
SHATTERED_SAVANNA | 1.10 | 0.0
SAVANNA | 1.20 | 0.0
SAVANNA | 1.20 | 0.0
SAVANNA | 1.20 | 0.0
DESERT | 2.00 | 0.0
NETHER | 2.00 | 0.0
DESERT_HILLS | 2.00 | 0.0
BADLANDS | 2.00 | 0.0
WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
BADLANDS_PLATEAU | 2.00 | 0.0
DESERT_LAKES | 2.00 | 0.0
ERODED_BADLANDS | 2.00 | 0.0
MODIFIED_WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
MODIFIED_BADLANDS_PLATEAU | 2.00 | 0.0
DESERT | 2.00 | 0.0
NETHER | 2.00 | 0.0
DESERT_HILLS | 2.00 | 0.0
BADLANDS | 2.00 | 0.0
WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
BADLANDS_PLATEAU | 2.00 | 0.0
DESERT_LAKES | 2.00 | 0.0
ERODED_BADLANDS | 2.00 | 0.0
MODIFIED_WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
MODIFIED_BADLANDS_PLATEAU | 2.00 | 0.0
DESERT | 2.00 | 0.0
NETHER | 2.00 | 0.0
DESERT_HILLS | 2.00 | 0.0
BADLANDS | 2.00 | 0.0
WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
BADLANDS_PLATEAU | 2.00 | 0.0
DESERT_LAKES | 2.00 | 0.0
ERODED_BADLANDS | 2.00 | 0.0
MODIFIED_WOODED_BADLANDS_PLATEAU | 2.00 | 0.0
MODIFIED_BADLANDS_PLATEAU | 2.00 | 0.0

**Comment by TheWranger** [comment]
Awesome, thanks.
