### ISSUE TITLE
World generation bug

### ISSUE THREAD

**Issue by GonzoDark** [BentoBoxWorld/AcidIsland#46]
**Description**
https://pastebin.com/rBsnuDgq

**Steps to reproduce the behavior:**
Starting the server with Bentobox and AcidIsland in the addons folder (no issues)
Stopping the server
Starting the server again (this is how we get the to relevant code)

**Expected behavior**
I expected multiverse to say "INFO Multiverse already knows about 'AcidIsland_world'!"

**Relevant Code**
21.02 22:17:29 [Server] INFO Multiverse already knows about 'BSkyBlock_world'!
21.02 22:17:29 [Server] INFO Success! Property generator was set to BentoBox
21.02 22:17:29 [Server] INFO Multiverse already knows about 'BSkyBlock_world_nether'!
21.02 22:17:29 [Server] INFO Success! Property generator was set to BentoBox
21.02 22:17:29 [Server] INFO Multiverse already knows about 'BSkyBlock_world_the_end'!
21.02 22:17:29 [Server] INFO Success! Property generator was set to BentoBox
**21.02 22:17:29 [Server] INFO CONSOLE: Starting import of world 'AcidIsland_world'...
21.02 22:17:29 [Server] WARN [BentoBox] Task #81 for BentoBox v1.2.1 generated an exception
21.02 22:17:29 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'mv' in plugin Multiverse-Core v2.6.0-b738**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
Flat file
Ubuntu 18.04 LTS
 - Java Version: [e.g. Java 8]
Java 8
 - BentoBox version: [e.g. 1.7.2.21]
1.2.1
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
BSkyBlock (1.3.0-SNAPSHOT)
SkyGrid 1.3.0-SNAPSHOT
AcidIsland 1.0
Challenges (0.5.1)
Level 0.2.0
 - Other plugins? [Do '/plugins' and copy/paste from the console]
Multiverse-Core

**Additional Information:**
I am pretty sure it is a bug with the AcidIsland plugin and not with multiverse

**Comment by tastybento** [comment]
It looks like the AcidIsland version is just too old. Here's the pre-release of 1.3.0
https://github.com/BentoBoxWorld/AcidIsland/releases/tag/1.3.0
