### ISSUE TITLE
Dispenser don't remove water if remote controlled

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#48]
**Description**
Dispenser don't remove water if remote controlled

**Steps to reproduce the behavior:**
1. Go to my island.
2. Place a dispenser and put water bucket.
3. Place redstone wire and place lever.
4. Use lever.

**Expected behavior**
Dispenser remove water if remote controlled

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Flat file
 - OS: Ubuntu 18.04
 - Java Version: Java 11.0.2
 - BentoBox version: 1.3.1
 - Addons installed?
```
17.03 15:14:54 [Server] INFO Running PAPER 1.13.2.
17.03 15:14:54 [Server] INFO BentoBox version: 1.3.1
17.03 15:14:54 [Server] INFO Loaded Game Worlds:
17.03 15:14:54 [Server] INFO AcidIsland_world (AcidIsland)
17.03 15:14:54 [Server] INFO Loaded Addons:
17.03 15:14:54 [Server] INFO AcidIsland 1.3.0
17.03 15:14:54 [Server] INFO Biomes 0.4.2
17.03 15:14:54 [Server] INFO Challenges 0.6.0-SNAPSHOT
17.03 15:14:54 [Server] INFO Level 1.2.2-SNAPSHOT
17.03 15:14:54 [Server] INFO Limits 0.1.0-SNAPSHOT
17.03 15:14:54 [Server] INFO WelcomeWarps 1.2-SNAPSHOT
```
 - Other plugins? [Do '/plugins' and copy/paste from the console]
`Plugins (86): AdditionsAPI, AdminVedelem, AdvancedAchievements, AntiAFK, antiRedstoneClock, AnvilRestrict, AsyncWorldEdit, BentoBox, BestViewDistance, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction*, ChestCommands, ChestShop, Citizens, CitizensCMD, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CratesPlusFix, CrazyAuctions, CreativeNbtControl, CustomOreGen, EnderContainers, EntityDetection*, EpicHeads, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, HolographicDisplays, ItemEdit*, JukeBox, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal, MobFarmManager, MobHeads, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, PickupSpawners, PlaceholderAPI, PlugMan, PocketGames, PomaAdditions, ProtocolLib*, RedstoneClockDetector*, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, Stats, SuperLuckyBlock-Pro, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, ViaBackwards*, ViaVersion*, Votifier, VotingPlugin, WDLCompanion*, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

**Additional context**
https://youtu.be/JblOHI6i06s?t=38

**Comment by tastybento** [comment]
This is normal vanilla operation: a water bucket in a dispenser never empties.

**Comment by BONNe** [comment]
> This is normal vanilla operation: a water bucket in a dispenser never empties.

emmm? thats not true. Water Bucket in dispenser empties, as lava bucket...

**Comment by tastybento** [comment]
Yes, it is true. If you push a button or lever, the bucket inside the dispenser will empty while the water is gushing out, but if you push it again then the water will stop and the bucket will refill. Please try it in vanilla.

**Comment by BONNe** [comment]
> Yes, it is true. If you push a button or lever, the bucket inside the dispenser will empty while the water is gushing out, but if you push it again then the water will stop and the bucket will refill. Please try it in vanilla.

Yes, and @andris155 created issue report that this behavior is not happening in acid island, if you power dispenser via redstone dust.
Check video :)

**Comment by tastybento** [comment]
I can't see any difference between Vanilla and AcidIsland. I made a video too:

https://youtu.be/p_SvJlyuP3I

What am I missing?

**Comment by BONNe** [comment]
https://www.youtube.com/watch?v=JblOHI6i06s&feature=youtu.be&t=38

**Comment by BONNe** [comment]
Ok, this is a vanilla bug.

I manage to get that it does not work in single player.

@andris155 ... use direct power to dispenser or repeater, as it solves this weird issue.
