### ISSUE TITLE
How to set island size

### ISSUE THREAD

**Issue by MoonDrinkWind** [BentoBoxWorld/AcidIsland#50]
How to set island size

**Comment by tastybento** [comment]
Which island distance?

config.yml has the island distance and protection ranges.

**Comment by MoonDrinkWind** [comment]
Do you just need to modify them?

**Comment by tastybento** [comment]
You can change them if you like. But do not change them mid game. What do you want to do exactly?

**Comment by MoonDrinkWind** [comment]
I just want change island size

**Comment by tastybento** [comment]
Yes, what do you mean by "island size". It could mean:

1. The distance between islands
2. The protected area size
3. The size of the island you start with

**Comment by MoonDrinkWind** [comment]
The protected area size

**Comment by tastybento** [comment]
Okay, then just change it in the config. That'll set it for every new island. If you want to change individual islands then you can use permissions. Read the config.yml for information:

```
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /bsbadmin range set <player> <new range>
  # or set this permission: bskyblock.island.range.<number>
  protection-range: 50
```

**Comment by MoonDrinkWind** [comment]
Thanks
