### ISSUE TITLE
Acid effect activating before conduit can take effect

### ISSUE THREAD

**Issue by Lolimi** [BentoBoxWorld/AcidIsland#51]
If a player enters water and then get the conduit effect, they get the acid effects before the conduit gets detected. So after nausea and blindness wear off, there are no more effects from the acid, so i guess you also shouldn't get them when entering the water with a conduit in range.

Maybe the effects could be delayed in order to give the conduit enough time to activate.

**Comment by tastybento** [comment]
Good catch! I'll check into this.

**Comment by tastybento** [comment]
I think conduit power could remove the effects of the acid. So, this'll be an enhancement.

**Comment by Lolimi** [comment]
since it already does remove the effect of the acid, but just to early, i don't think it is an enhancement, the conduit makes you not have the acid effect, but not if you jump into the water, because you don't get the conduit effect instantly

**Comment by tastybento** [comment]
I understand. It looks like it takes about 2 seconds for conduit power to kick in, so to support this feature I'd need to wait for 2 seconds before acid kicks in. Hmm, I'm not sure waiting for two seconds will be a good idea because that'll take the risk out of normal acid island play.

**Comment by Lolimi** [comment]
Maybe you could make it a config option how long it should wait before giving the effect, that way server owners can choose for themselves, if they want the conduit to work or the risk to be higher.

**Comment by tastybento** [comment]
Okay, done.
