### ISSUE TITLE
1.14.1 only support lowercase world names

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#52]
1.14.1 only support lowercase world names.
But AcidIsland default used names is AcidIsland_world, AcidIsland_world_nether, AcidIsland_world_the_end.
How to update worlds and databases without data loss?

**Comment by Poslovitch** [comment]
We will think about that for BentoBox's 1.6.0, when we will start working on proper and full 1.14 support.

**Comment by tastybento** [comment]
It'll be supported. Do not worry.

**Comment by tastybento** [comment]
Done.
