### ISSUE TITLE
Island reset cause very big lag

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#59]
**Description**
Island reset cause very big lag

**Steps to reproduce the behavior:**
1. Go to 'my island'
2. write /is reset
3. select island and reset

**Expected behavior**
/is reset cause very big lag

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Json
 - OS: Ubuntu 18.04
 - Java Version: OpenJDK 11.0.4
 - BentoBox version: 1.7.0-SNAPSHOT-b1359
 - Addons installed?
[21:35:44 INFO]: Running PAPER 1.14.4.
[21:35:44 INFO]: BentoBox version: 1.7.0-SNAPSHOT-b1359
[21:35:44 INFO]: Database: JSON
[21:35:44 INFO]: Loaded Game Worlds:
[21:35:44 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[21:35:44 INFO]: Loaded Addons:
[21:35:44 INFO]: AcidIsland 1.7.0-SNAPSHOT-b436
[21:35:44 INFO]: Biomes 1.6.0.2-SNAPSHOT-b135
[21:35:44 INFO]: Challenges 0.8.0-SNAPSHOT-#347
[21:35:44 INFO]: Greenhouses 0.3.2-SNAPSHOT
[21:35:44 INFO]: Level 1.7.0-SNAPSHOT-b282
[21:35:44 INFO]: Limits 1.6.0
 - Other plugins?
Plugins (89): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, BentoBox, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomOreGen, Duels, EnderContainers, EntityDetection, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, HeadDatabase*, HolographicDisplays, JukeBox, Kemkedes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, PickupSpawners, PlaceholderAPI*, PlayerHeads, PlugMan, PocketGames, PomaAdditions, ProtocolLib, RedstoneClockDetector, SAML, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, Statscraft*, SuperLuckyBlock, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

**Additional context**
https://www.youtube.com/watch?v=ZMAAIz8Vhh4

**Comment by tastybento** [comment]
I reduced the number of chunks regenerated per tick. It's now at the minimum. You'll need to use the latest BentoBox build from Jenkins to see the option in the BentoBox config.yml.

f9a5f05987b761120da9506c6fcd5b4451f78832
