### ISSUE TITLE
Option to have lava in the nether instead of water

### ISSUE THREAD

**Issue by Bobcycle** [BentoBoxWorld/AcidIsland#63]
I would love an option to enable lava to be generated instead of water in the nether since this allows for one, more light and secondly it's basically what the nether is about.

Maybe something like `lava-instead-of-water: true/false`

It's a small feature, but definitely something I (and others) would love to have.
I have tried using custom generators but it didn't work out too well for me.

**Comment by johncsuti** [comment]
Make buckets not work in the nether then if the server admin sets lava_nether=true?

**Comment by BONNe** [comment]
Tasty, maybe you need to look into this again.

Since 1.17 lava is a renewable resource. So I do not think it will be a huge deal if in the acid island it will be more available than in other gamemodes.

**Comment by Max2124** [comment]
> I would love an option to enable lava to be generated instead of water in the nether since this allows for one, more light and secondly it's basically what the nether is about.
> 
> Maybe something like `lava-instead-of-water: true/false`
> 
> It's a small feature, but definitely something I (and others) would love to have. I have tried using custom generators but it didn't work out too well for me.



Just wanted to "remember" this feature and also maybe if it's possible giving Admins the opportunity to change or choose between water and lava in all worlds. (If that's possible).  :)

**Comment by tastybento** [comment]
@Max2124 This is done. Note that I adjusted the nether and end islands.
