### ISSUE TITLE
Problem with the island schematic

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#65]
Hi, I performed the procedure using the / acid blueprint commands to create the schematic of the island.

There is a problem: the blocks of "air" inside the island (I created a subterranean room) are filled with water .. how can this problem be solved?

**Comment by Manu5656** [comment]
Solved, I tried again and the problem didn't show up again

**Comment by BONNe** [comment]
By default, blueprints do not copy air blocks, as in most situations it is not useful to do it.
To copy air, you need to add parameter `air` when you copy blueprint before saving.

**Comment by Manu5656** [comment]
Ok, thanks!
