### ISSUE TITLE
Purge inactive islands

### ISSUE THREAD

**Issue by ScuroK** [BentoBoxWorld/AcidIsland#67]
Hi

Is there a command to remove inactive islands like there was in the old acidisland? i really need this otherwise i cant use the plugin. I didnt find it on the command list.

**Comment by tastybento** [comment]
Yes, it’s there. Try ‘/acid purge’.

**Comment by ScuroK** [comment]
Ok thx. Hey dude i just have to ask:

Am i save to run this plugin now? Is it stable so far?
Because there is still no release on spigot and i dont want to lose another island world (like i did with acidisland).
I really love acidisland and i think you are a great dev. I just want to make sure it will be continued. Because i cant find another island plugin on spigot wich i can trust right now.

**Comment by tastybento** [comment]
There’s no guarantee of course but we’re seeing pretty good stability right now and I expect we’ll release on spigot at some point. You can check out BStats and see we’re on 600 servers. I also recommend you try the Discord and ask other admins. It’s an actively developed plugin so we’ll fix bugs.

**Comment by ScuroK** [comment]
@tastybento 
Hey i just reported an issue regarding purge. it deletet most if not all of our islands. pls check it out:
https://github.com/BentoBoxWorld/BentoBox/issues/1333
