### ISSUE TITLE
Phantoms spawn in Nether and the end

### ISSUE THREAD

**Issue by thunderlight411** [BentoBoxWorld/AcidIsland#74]
**Description**
Phantoms spawn in Nether and the end

**Steps to reproduce the behavior:**
1. don't sleep for a cople of days
2. join the Nether or the end and wait till they spawn

**Expected behavior**

**Server Information:**
 - Database being used (Flat file, MySQL, Mongo): Flatfile
 - OS: CentOS 7.7.1908
 - Java Version: Java 8
 - BentoBox version: 1.9.0
 - Addons installed?
02.12 21:00:23 [Server] INFO Running PAPER 1.14.4.
02.12 21:00:23 [Server] INFO BentoBox version: 1.9.0
02.12 21:00:23 [Server] INFO Database: YAML2JSON
02.12 21:00:23 [Server] INFO Loaded Game Worlds:
02.12 21:00:23 [Server] INFO acidisland_world (AcidIsland): Overworld, Nether, End
02.12 21:00:23 [Server] INFO bskyblock_world (BSkyBlock): Overworld, Nether, End
02.12 21:00:23 [Server] INFO caveblock-world (CaveBlock): Overworld, Nether, End
02.12 21:00:23 [Server] INFO Loaded Addons:
02.12 21:00:23 [Server] INFO AcidIsland 1.9.0 (ENABLED)
02.12 21:00:23 [Server] INFO Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
02.12 21:00:23 [Server] INFO BSkyBlock 1.9.0 (ENABLED)
02.12 21:00:23 [Server] INFO CaveBlock 1.9.0-SNAPSHOT-b243 (ENABLED)
02.12 21:00:23 [Server] INFO Challenges 0.9.0-SNAPSHOT-#394 (ENABLED)
02.12 21:00:23 [Server] INFO Greenhouses 0.4.5-SNAPSHOT-b113 (ENABLED)
02.12 21:00:23 [Server] INFO Level 1.9.1-SNAPSHOT-b328 (ENABLED)
02.12 21:00:23 [Server] INFO MagicCobblestoneGenerator 1.7.1-SNAPSHOT-#86 (ENABLED)
02.12 21:00:23 [Server] INFO Warps 1.8.2 (ENABLED)
 - Other plugins?
[21:02:07] [Server thread/INFO]: Plugins (29): BannerBoard*, BentoBox, BossShopPro, BungeeTabListPlus*, BuycraftX, ChestSort, CMI, CMIEInjector*, CoreProtect, dynmap*, IPWhitelist*, JustEssentials, JustRank, LuckPerms, mcMMO, MorphRedeem, MultiChatSpigot, PerWorldInventory, PlaceholderAPI, Plan, ProtocolLib, TitleAPI, TokenManager, UltimateVotes, Vault, WorldEdit, WorldEditGlobalizerBukkit*, WorldEditSUI, WorldGuard

**Comment by tastybento** [comment]
I don't think there's anything I can do about this - I don't control when they spawn or why - it's up to the server. Do you have a nether roof/ceiling?

**Comment by BONNe** [comment]
Just a side question... which biome is in the end and nether?

**Comment by tastybento** [comment]
It _should be_ NETHER and END, but that's a good question...

**Comment by thunderlight411** [comment]
Can confirm that the biomes are Nether and Small_end_island

There is a roof in the nether at level 255
and offcorse the End don't have any roof in there

**Comment by BONNe** [comment]
So, it is not BentoBox fault... at least not tasty and poslovitch...
mine is questionable :D

It is a spigot that processes phantom spawning. I looked into it, and it should not spawn phantoms should spawn only if there is sky access, which should not be in nether and end.

When I will get some free time, I will investigate the issue and check if there is something messed up with sky access.

**Comment by g3forcemc** [comment]
Just use wordguard and disable them.
