### ISSUE TITLE
Rain makes a permanent effect (AcidIsland

### ISSUE THREAD

**Issue by R4zzerYT** [BentoBoxWorld/AcidIsland#83]
#### Describe the bug

The Rain adds a permanent effect, but it should only be 30 seconds

#### Steps to reproduce the behavior

https://youtu.be/a2bblwYJQvw

#### Expected behavior

30 seconds effects, but not permanent.

#### Screenshots and videos (Optional)

https://youtu.be/a2bblwYJQvw

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2
BentoBox version: 1.11.2-SNAPSHOT-b1655
Database: JSON
Loaded Game Worlds:
insel-welt (Stranded): Insel-Welt, Nether, The End

Loaded Addons:
AcidIsland 1.11.1-SNAPSHOT-b655 (ENABLED)
Challenges
```

#### Plugins (Optional)

```
over 40. But i dont think that one of my plugins makes that error.
```
 
### Additional context (Optional)

I generally think that the 30 seconds are too long.
It would be cool, if we can change that to 10 or something like this in the config.

**Comment by tastybento** [comment]
Please try the latest AcidIsland build from the CI and see if it does what you want.
