### ISSUE TITLE
AcidTask cause server lag

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/AcidIsland#84]
**Description**
AcidTask cause server lag

**Steps to reproduce the behavior:**
Play 15+ players on server.

**Expected behavior**
AcidTask no cause server lag

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): JSON
 - OS: Ubuntu
 - Java Version: Java 11
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed?
```
[19:37:53 INFO]: AcidIsland 1.12.1-SNAPSHOT-b716 (ENABLED)
[19:37:53 INFO]: Biomes 1.6.0.1-SNAPSHOT-b152 (ENABLED)
[19:37:53 INFO]: Challenges 0.9.0-SNAPSHOT-b400 (ENABLED)
[19:37:53 INFO]: Chat 1.0.4 (ENABLED)
[19:37:53 INFO]: DimensionalTrees 1.6.0-SNAPSHOT-b80 (ENABLED)
[19:37:53 INFO]: Greenhouses 1.0.2-SNAPSHOT-b215 (ENABLED)
[19:37:53 INFO]: Level 1.9.4-SNAPSHOT-b345 (ENABLED)
[19:37:53 INFO]: Likes 1.7.0-SNAPSHOT-b21 (ENABLED)
[19:37:53 INFO]: MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b101 (ENABLED)
[19:37:53 INFO]: Warps 1.9.3-SNAPSHOT-b222 (ENABLED)
```
 - Other plugins?
`Plugins (83): AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, ArmorStandEditor, AsyncWorldEdit, BentoBox, BetterGUI, ChangeSkin, ChatControl, ChatReaction, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, Duels, EasterEggs*, EnderContainers, EntityDetection, EntityTrackerFixer, Ercgenerator, Essentials, EssentialsChat, EssentialsSpawn, EventekGUI, EventRendszer, HeadDatabase*, HolographicDisplays, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, MyPet, NametagEdit*, NoCheatPlus, OpenInv, PickupSpawners, PlaceholderAPI, PlugMan, PocketGames, ProtocolLib, RedstoneClockDetector, RemoveUnbreaking, RestrictedCreative, ShopGUIPlus, Shopkeepers, SignEdit, Sleepy*, StaffChat, StaffTime, SuperLuckyBlock, TimeIsMoney*, TitleManager, TokenManager, TokenShopEditor, TokenStaff*, TreasureChest, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge`

**Additional context**
<img width="1116" alt="Capture" src="https://user-images.githubusercontent.com/8324198/78924334-e5ab1180-7a99-11ea-80f2-244b0347df96.PNG">

https://timings.aikar.co/?id=b07dfa498f9f4e90a88f738d804bb642

**Comment by tastybento** [comment]
I've changed the approach to only burn mobs and items if the chunks are already loaded.

**Comment by andris155** [comment]
Maybe better.
