### ISSUE TITLE
Water Elevators at AcidIsland

### ISSUE THREAD

**Issue by R4zzerYT** [BentoBoxWorld/AcidIsland#85]
#### Is your feature request related to a problem?

No.

#### Describe the solution you'd like us to implement.

If my players build a water elevator at there acidisland island, they get damage. Can you please add a feature to prevent this? I know the water is acid, but wouldn't it make sense if this water has no acid because it's in an elevator?

#### Describe alternatives you've considered.

idk

**Comment by tastybento** [comment]
You could jump in a boat and ride up the water elevator?

**Comment by tastybento** [comment]
This isn't really compatible with AcidIsland, sorry.
