### ISSUE TITLE
Unable to finish novice quest on acid island

### ISSUE THREAD

**Issue by Azlanne** [BentoBoxWorld/AcidIsland#86]
**Description**
I play on a server with the acid island and I can't complete the quest "apple picker" because acacias tree don't give apple.

**Steps to reproduce the behavior:**
1. type /is challenges
2. place cursor on the apple picker quests : to complete it we need 5 apples
3. Apples falls from oak, birch trees, but not from acacia. How do I get the apples to finish this quest ?

**Expected behavior**

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - OS: windows 10
 - Java Version: Java 8 
 - BentoBox version: don't know, it's not my server
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by Azlanne** [comment]
The fact that we cannot get the apple, keeps us from getting the tree saplings, and the reward is 4 saplings of each tree except the oak one. We need the oak saplings to get oak log to finish another quest. In the settings, there is no place where we can change the starter kit to add apples and or saplings in  the beginning chests.

**Comment by BONNe** [comment]
This is not an issue at all.
Default challenges are mostly built for SkyBlock. And it is just a template in the short run. 
As well as blueprints for AcidIsland is changeable. You can add oak sapling in the chest if you want. 

Also, you can edit challenges via the in-game menu and remove apple one, if you do not like it, or change requirements.

Of course, a specific challenge set for AcidIsland, SkyGrid, OneBlock, and CaveBlock would be awesome, but it would take time to make and take time away from fixing bugs and adding new features :D

**Comment by tastybento** [comment]
@Azlanne Yes, Bonne is right, I recommend you tweak your apple quest to require some other item that could be gathered like fish, maybe. Good luck!
