### ISSUE TITLE
None or very few animals spawning on grass in island

### ISSUE THREAD

**Issue by KleinDevDE** [BentoBoxWorld/AcidIsland#91]
**Description**
I have created a test area of grass using `//fill grass_block 20` and put enough torches on it so that there is a light level of 15 over the whole area.

I've been waiting several days inGame until an animal finally spawns, but nothing happens.

**Steps to reproduce the behavior:**

**Expected behavior**
Animals spawning

**Screenshots**
![image](https://user-images.githubusercontent.com/13904220/87858612-731abf00-c92f-11ea-9efe-49e64b4224fc.png)

**Server Information:**
 - Database being used (Flat file, MySQL, Mongo): Flat file
 - OS: Debian 9.11
 - Java Version: 1.8.0_201
 - BentoBox version: 1.13.1
 - Addons installed?
```
> bentobox version
[01:34:59 INFO]: Running PAPER 1.15.2.
[01:34:59 INFO]: BentoBox version: 1.13.1
[01:34:59 INFO]: Database: JSON
[01:34:59 INFO]: Loaded Game Worlds:
[01:34:59 INFO]: acidisland_world (AcidIsland): Overworld, Nether, The End
[01:34:59 INFO]: Loaded Addons:
[01:34:59 INFO]: AcidIsland 1.13.1 (ENABLED)
[01:34:59 INFO]: Biomes 1.7.0 (ENABLED)
[01:34:59 INFO]: Challenges 0.8.2 (ENABLED)
[01:34:59 INFO]: Level 1.9.3 (ENABLED)
[01:34:59 INFO]: Likes 1.7.1 (ENABLED)
[01:34:59 INFO]: Limits 1.12.1 (ENABLED)
[01:34:59 INFO]: MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
[01:34:59 INFO]: Warps 1.9.5 (ENABLED)
```
 - Other plugins?
```
> pl
[01:35:12 INFO]: Plugins (11): BentoBox, ChatMentions*, CoreProtect, Essentials, EssentialsSpawn, HolographicDisplays, LuckPerms, Multiverse-Core, SkyBlockStarter, Spawnertools, WorldEdit, WorldGuard
>

//SkyBlockStarter only add /is as alias for /ai
//SPawnertools is only for editing spawner blocks
```
**Additional context**
Limits/config.yml
```yaml
# Game Modes covered by limits
gamemodes:
- AcidIsland
- BSkyBlock
- CaveBock

# Permissions
# Island owners can be given permissions that override all general settings
# Format is GAME-MODE-NAME.island.limit.MATERIAL.LIMIT
# example: bskyblock.island.limit.hopper.10
# permission activates when player logs in.
#
# Cooldown for player recount command in seconds
cooldown: 120

# General block limiting
# Use this section to limit how many blocks can be added to an island.
# 0 means the item will be blocked from placement completely.
# These limits apply to every game mode world
blocklimits:
  HOPPER: 30
# This section is for world-specific limits and overrides the general limit
# Specify each world you want to limit individually (including nether and end worlds)
# If these worlds are not covered by the game modes above, nothing will happen
worlds:

# Default entity limits within a player's island space (protected area and to island limit).
# A limit of 5 will allow up to 5 entities in over world, 5 in nether and 5 in the end.
# Affects all types of creature spawning. Also includes entities like MINECARTS.
# Note: Only the first 49 limited blocks and entities are shown in the limits GUI.
entitylimits:
  ENDERMAN: 5
  CHICKEN: 10
  pig_ZOMbIe: 15
```

**Comment by tastybento** [comment]
This is weird. I haven't been able to test this, but it obviously shouldn't happen. Do you have mob spawning turned on in the island settings?

**Comment by Vimppura69** [comment]
If you have the overworld biome set up as WARM_OCEAN (which is the default), you cannot get any animals by natural spawning. I had the same issue and realized that they cannot spawn because of the biome. At our server we decided to add spawn eggs as a reward for some challenges to fix this issue and make animals part of the fun. You can also try changing the biome from into like plains etc or download Bento's biome addon and give players the possibility to change the biome for their own island.

At least I hope this is the case for this spesific issue...

**Comment by KleinDevDE** [comment]
Yeah it was turned on.
Now it seems to be fixed, I changed the biome of the hole island then changed back
