### ISSUE TITLE
Stone generation in nether and end worlds

### ISSUE THREAD

**Issue by piotrskibapl** [BentoBoxWorld/AcidIsland#94]
**Description**
Currently, on the regular acid worlds, the stone generation by lava flowing onto the water is blocked. However, in nether/end worlds it's not.

**Steps to reproduce the behavior:**
1. Go to the nether or end world
2. Place lava that will flow onto the water
3. The stone is generated under the lava

**Expected behavior**
The stone should not be created, as in the regular world.

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): JSON
 - OS: Linux
 - Java Version: Java 8
 - BentoBox version: 1.14.2
 - Addons installed?

```
AcidIsland 1.14.3-SNAPSHOT-b859
Challenges 0.8.3
ControlPanel 1.7.0
DimensionalTrees 1.6.0
Level 2.4.0
Limits 1.14.0
Warps 1.10.0
```

**Comment by tastybento** [comment]
Thanks for the report. It'll be in the next build.
