### ISSUE TITLE
Coop and Trust

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#97]
Hi, the players with the coop or the trust cannot build or do anything else. I've had this problem in the past but you gave me some values to add in the config and I solved it.

Currently in the flags section there is this:

`  # Ranks are: Visitor = 0, Member = 900, Owner = 1000`

But there are no written values for co-ops and trusts.

Searching on Github I found this list of yours (which is the same as the one I had seen in the past):
`VISITOR   = 0
COOP      = 200
TRUSTED   = 400
MEMBER    = 500
SUB-OWNER = 900
OWNER     = 1000`

But even if I put the value "200" or lower in the flags, the problem still remains the same.

Have the values changed? If so, which are the correct ones that I have to enter to give all the permissions also to the players with the coop or trust? Thank you and good day.

**Comment by tastybento** [comment]
Island owners can decide what ranks and do what on their island via the `/island settings` menu (if they have the perms). So, that's the first thing to check. Changing config.yml sets the default settings for islands. If an owner subsequently changes them, then they can be overwritten. If you want to reset settings flags for all islands in one go, edit the config.yml how you want and then do `/bsb resetflags` and then confirm. If you just want to reset some flags, you can do that with that command too - just use tab-complete to see the options.

**Comment by Manu5656** [comment]
OK thank you very much.

One last question: How do I change the permissions differences between sub-owner and owner for example?
I would like to give the sub-owner permission to be able to ban members from the island, such as the owner

**Comment by tastybento** [comment]
As the owner, do `/is settings` and then select command ranks. You can set who can do commands there.

**Comment by Manu5656** [comment]
Ok thank you!
