### ISSUE TITLE
Need workarround for portals

### ISSUE THREAD

**Issue by ScuroK** [BentoBoxWorld/AcidIsland#98]
Hi there. Back in the days acidisland was able to overwrite the portal behaviour (end and nether) even if those were turned off.
now this is not possible anymore so we are forced to activate the portals on the server globally.

my problem is that i run a multiworld server with several seperate worlds. if portals are activated it messes everything up. for example: players teleport between two end worlds if they enter the exit portal of one end world.

i spendt a long time searching for solutions but it is very hard.

could you try to find a workarround to make AI-portals work again even if portals are turned off? i know it seems like a small thing but for us it is very bad. :(

EDIT: One idea would be an option to have AI-Portals contain particles instead of vanilla portal blocks maybe?

**Comment by ScuroK** [comment]
it is hard to explain my problem in detail. i hope u understand im a long time server owner and i know if something is not possible to solve myself. :S

if u do need more details to understand the importance let me know and i will try my best.

**Comment by ScuroK** [comment]
Update: i use skript to fix me specific issues for now.

**Comment by tastybento** [comment]
This PR will enable portals even if the nether and end are disabled on the server: https://github.com/BentoBoxWorld/BentoBox/pull/1539

**Comment by Poslovitch** [comment]
Closing this as this is fixed by BentoBoxWorld/BentoBox#1539
